import type { Metadata } from "next";
import "./globals.css";
import { OverlayProvider } from "@/hooks/useOverlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <OverlayProvider>{children}</OverlayProvider>
      </body>
    </html>
  );
}
